version: "3.8"

services:
  postgres:
    image: postgres:13 # Using the official PostgreSQL image
    container_name: FinShark-postgres-bab
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=FinShark
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: FinShark-dotnetWebApi-backend-bab
    ports:
      - "5222:5222"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection="Host=localhost;Database=FinShark;Username=postgres;Password=admin";
      - ASPNETCORE_URLS=http://+:5222
    volumes:
      - ./api:/app
    depends_on:
      - postgres
    # restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: FinShark-react-frontend-bab
    ports:
      - "3000:80"
    depends_on:
      - backend
    # restart: always
volumes:
  postgres-data:
