# version: "3.8"

services:
  postgres:
    image: postgres:13 # Using the official PostgreSQL image
    container_name: FinShark-postgres-bab
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=FinShark
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

  backend:
    build: .
    container_name: FinShark-dotnetWebApi-react-coupled-bab
    ports:
      - "5222:5222"
    env_file:
      - ./.env # Load environment variables
    environment:
      ASPNETCORE_ENVIRONMENT: production
      ASPNETCORE_URLS: http://+:5222
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=FinShark;Username=postgres;Password=admin;

    depends_on:
      - postgres
    # restart: always

    volumes:
      - .:/app
      - ./keys:/root/.aspnet/DataProtection-Keys

volumes:
  postgres-data:
